//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Cliente {
    
    
    public partial class Cliente_cu_buscar {
        
        /// <summary>
        /// Cliente_cu_select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_MostrarUnico Cliente_cu_select;
        
        /// <summary>
        /// lblMensajeError_Buscar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMensajeError_Buscar;
    }
}
