//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.WS_Serviciotecnico {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Serviciotecnico.WS_ServiciotecnicoSoap")]
    public interface WS_ServiciotecnicoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SitioWeb.WS_Serviciotecnico.SelectResponse Select(SitioWeb.WS_Serviciotecnico.SelectRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectResponse> SelectAsync(SitioWeb.WS_Serviciotecnico.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDynamic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SitioWeb.WS_Serviciotecnico.SelectDynamicResponse SelectDynamic(SitioWeb.WS_Serviciotecnico.SelectDynamicRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDynamic", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectDynamicResponse> SelectDynamicAsync(SitioWeb.WS_Serviciotecnico.SelectDynamicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SitioWeb.WS_Serviciotecnico.SelectDataTableResponse SelectDataTable(SitioWeb.WS_Serviciotecnico.SelectDataTableRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectDataTableResponse> SelectDataTableAsync(SitioWeb.WS_Serviciotecnico.SelectDataTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SitioWeb.WS_Serviciotecnico.SelectFirstResponse SelectFirst(SitioWeb.WS_Serviciotecnico.SelectFirstRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Serviciotecnico.SelectFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string InsertInto(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<string> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string Update(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<string> UpdateAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        string Delete(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resultado")]
        System.Threading.Tasks.Task<string> DeleteAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassServiciotecnico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidserviciotecnicoField;
        
        private System.Nullable<int> codservicioField;
        
        private string uidclienteField;
        
        private string uidempleadoField;
        
        private System.Nullable<System.DateTime> fechaingresoField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string problemasugeridoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uidserviciotecnico {
            get {
                return this.uidserviciotecnicoField;
            }
            set {
                this.uidserviciotecnicoField = value;
                this.RaisePropertyChanged("uidserviciotecnico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> codservicio {
            get {
                return this.codservicioField;
            }
            set {
                this.codservicioField = value;
                this.RaisePropertyChanged("codservicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string uidcliente {
            get {
                return this.uidclienteField;
            }
            set {
                this.uidclienteField = value;
                this.RaisePropertyChanged("uidcliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string uidempleado {
            get {
                return this.uidempleadoField;
            }
            set {
                this.uidempleadoField = value;
                this.RaisePropertyChanged("uidempleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> fechaingreso {
            get {
                return this.fechaingresoField;
            }
            set {
                this.fechaingresoField = value;
                this.RaisePropertyChanged("fechaingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string problemasugerido {
            get {
                return this.problemasugeridoField;
            }
            set {
                this.problemasugeridoField = value;
                this.RaisePropertyChanged("problemasugerido");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UidUserLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EstadoExistencia;
        
        public SelectRequest() {
        }
        
        public SelectRequest(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] SelectResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string resultado;
        
        public SelectResponse() {
        }
        
        public SelectResponse(SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] SelectResult, string resultado) {
            this.SelectResult = SelectResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectDynamic", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectDynamicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UidUserLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EstadoExistencia;
        
        public SelectDynamicRequest() {
        }
        
        public SelectDynamicRequest(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectDynamicResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectDynamicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] SelectDynamicResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string resultado;
        
        public SelectDynamicResponse() {
        }
        
        public SelectDynamicResponse(SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] SelectDynamicResult, string resultado) {
            this.SelectDynamicResult = SelectDynamicResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectDataTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectDataTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UidUserLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EstadoExistencia;
        
        public SelectDataTableRequest() {
        }
        
        public SelectDataTableRequest(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectDataTableResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectDataTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable SelectDataTableResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string resultado;
        
        public SelectDataTableResponse() {
        }
        
        public SelectDataTableResponse(System.Data.DataTable SelectDataTableResult, string resultado) {
            this.SelectDataTableResult = SelectDataTableResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFirst", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UidUserLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string uidserviciotecnico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string EstadoExistencia;
        
        public SelectFirstRequest() {
        }
        
        public SelectFirstRequest(string UidUserLogin, string uidserviciotecnico, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.uidserviciotecnico = uidserviciotecnico;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectFirstResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico SelectFirstResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string resultado;
        
        public SelectFirstResponse() {
        }
        
        public SelectFirstResponse(SitioWeb.WS_Serviciotecnico.ClassServiciotecnico SelectFirstResult, string resultado) {
            this.SelectFirstResult = SelectFirstResult;
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ServiciotecnicoSoapChannel : SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ServiciotecnicoSoapClient : System.ServiceModel.ClientBase<SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap>, SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap {
        
        public WS_ServiciotecnicoSoapClient() {
        }
        
        public WS_ServiciotecnicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ServiciotecnicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ServiciotecnicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ServiciotecnicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Serviciotecnico.SelectResponse SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap.Select(SitioWeb.WS_Serviciotecnico.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] Select(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Serviciotecnico.SelectRequest inValue = new SitioWeb.WS_Serviciotecnico.SelectRequest();
            inValue.UidUserLogin = UidUserLogin;
            inValue.VALUE = VALUE;
            inValue.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Serviciotecnico.SelectResponse retVal = ((SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap)(this)).Select(inValue);
            resultado = retVal.resultado;
            return retVal.SelectResult;
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectResponse> SelectAsync(SitioWeb.WS_Serviciotecnico.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Serviciotecnico.SelectDynamicResponse SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap.SelectDynamic(SitioWeb.WS_Serviciotecnico.SelectDynamicRequest request) {
            return base.Channel.SelectDynamic(request);
        }
        
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico[] SelectDynamic(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Serviciotecnico.SelectDynamicRequest inValue = new SitioWeb.WS_Serviciotecnico.SelectDynamicRequest();
            inValue.UidUserLogin = UidUserLogin;
            inValue.VALUE = VALUE;
            inValue.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Serviciotecnico.SelectDynamicResponse retVal = ((SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap)(this)).SelectDynamic(inValue);
            resultado = retVal.resultado;
            return retVal.SelectDynamicResult;
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectDynamicResponse> SelectDynamicAsync(SitioWeb.WS_Serviciotecnico.SelectDynamicRequest request) {
            return base.Channel.SelectDynamicAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Serviciotecnico.SelectDataTableResponse SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap.SelectDataTable(SitioWeb.WS_Serviciotecnico.SelectDataTableRequest request) {
            return base.Channel.SelectDataTable(request);
        }
        
        public System.Data.DataTable SelectDataTable(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Serviciotecnico.SelectDataTableRequest inValue = new SitioWeb.WS_Serviciotecnico.SelectDataTableRequest();
            inValue.UidUserLogin = UidUserLogin;
            inValue.VALUE = VALUE;
            inValue.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Serviciotecnico.SelectDataTableResponse retVal = ((SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap)(this)).SelectDataTable(inValue);
            resultado = retVal.resultado;
            return retVal.SelectDataTableResult;
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectDataTableResponse> SelectDataTableAsync(SitioWeb.WS_Serviciotecnico.SelectDataTableRequest request) {
            return base.Channel.SelectDataTableAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Serviciotecnico.SelectFirstResponse SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap.SelectFirst(SitioWeb.WS_Serviciotecnico.SelectFirstRequest request) {
            return base.Channel.SelectFirst(request);
        }
        
        public SitioWeb.WS_Serviciotecnico.ClassServiciotecnico SelectFirst(string UidUserLogin, string uidserviciotecnico, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Serviciotecnico.SelectFirstRequest inValue = new SitioWeb.WS_Serviciotecnico.SelectFirstRequest();
            inValue.UidUserLogin = UidUserLogin;
            inValue.uidserviciotecnico = uidserviciotecnico;
            inValue.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Serviciotecnico.SelectFirstResponse retVal = ((SitioWeb.WS_Serviciotecnico.WS_ServiciotecnicoSoap)(this)).SelectFirst(inValue);
            resultado = retVal.resultado;
            return retVal.SelectFirstResult;
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Serviciotecnico.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Serviciotecnico.SelectFirstRequest request) {
            return base.Channel.SelectFirstAsync(request);
        }
        
        public string InsertInto(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.InsertInto(UidUserLogin, VALUE);
        }
        
        public System.Threading.Tasks.Task<string> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.InsertIntoAsync(UidUserLogin, VALUE);
        }
        
        public string Update(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.Update(UidUserLogin, VALUE);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.UpdateAsync(UidUserLogin, VALUE);
        }
        
        public string Delete(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.Delete(UidUserLogin, VALUE);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(string UidUserLogin, SitioWeb.WS_Serviciotecnico.ClassServiciotecnico VALUE) {
            return base.Channel.DeleteAsync(UidUserLogin, VALUE);
        }
    }
}
