//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Parametros {
    
    
    public partial class Parametros_CU_Delete {
        
    
        /// <summary>
        /// txt_buscarDeleteUIDParametros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_buscarDeleteUIDParametros;
        
		
        /// <summary>
        /// btnDeleteParametrosMostrarModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDeleteParametrosMostrarModal;
        
		
			       
                /// <summary>
                /// Control lbl_uidparmetro_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidparmetro_delete;
        
                /// <summary>
                /// Control txt_uidparmetro_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_uidparmetro_delete;  
			       
                /// <summary>
                /// Control lbl_moduloreferencia_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_moduloreferencia_delete;
        
                /// <summary>
                /// Control txt_moduloreferencia_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_moduloreferencia_delete;  
			       
                /// <summary>
                /// Control lbl_value_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_value_delete;
        
                /// <summary>
                /// Control txt_value_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_value_delete;  
			       
                /// <summary>
                /// Control lbl_textshort_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_textshort_delete;
        
                /// <summary>
                /// Control txt_textshort_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_textshort_delete;  
			       
                /// <summary>
                /// Control lbl_textlong_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_textlong_delete;
        
                /// <summary>
                /// Control txt_textlong_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_textlong_delete;  
        
        /// <summary>
        /// lblMensajeError_delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMensajeError_delete;
        
        /// <summary>
        /// btnGuardarEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGuardarEliminar;

	}
}
