//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.WS_Empresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassEmpresa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassEmpresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uid_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string representantelegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux10Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uid_empresa {
            get {
                return this.uid_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.uid_empresaField, value) != true)) {
                    this.uid_empresaField = value;
                    this.RaisePropertyChanged("uid_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                if ((object.ReferenceEquals(this.rucField, value) != true)) {
                    this.rucField = value;
                    this.RaisePropertyChanged("ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string representantelegal {
            get {
                return this.representantelegalField;
            }
            set {
                if ((object.ReferenceEquals(this.representantelegalField, value) != true)) {
                    this.representantelegalField = value;
                    this.RaisePropertyChanged("representantelegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string aux1 {
            get {
                return this.aux1Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux1Field, value) != true)) {
                    this.aux1Field = value;
                    this.RaisePropertyChanged("aux1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string aux2 {
            get {
                return this.aux2Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux2Field, value) != true)) {
                    this.aux2Field = value;
                    this.RaisePropertyChanged("aux2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string aux3 {
            get {
                return this.aux3Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux3Field, value) != true)) {
                    this.aux3Field = value;
                    this.RaisePropertyChanged("aux3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string aux4 {
            get {
                return this.aux4Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux4Field, value) != true)) {
                    this.aux4Field = value;
                    this.RaisePropertyChanged("aux4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string aux5 {
            get {
                return this.aux5Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux5Field, value) != true)) {
                    this.aux5Field = value;
                    this.RaisePropertyChanged("aux5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string aux6 {
            get {
                return this.aux6Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux6Field, value) != true)) {
                    this.aux6Field = value;
                    this.RaisePropertyChanged("aux6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string aux7 {
            get {
                return this.aux7Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux7Field, value) != true)) {
                    this.aux7Field = value;
                    this.RaisePropertyChanged("aux7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string aux8 {
            get {
                return this.aux8Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux8Field, value) != true)) {
                    this.aux8Field = value;
                    this.RaisePropertyChanged("aux8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string aux9 {
            get {
                return this.aux9Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux9Field, value) != true)) {
                    this.aux9Field = value;
                    this.RaisePropertyChanged("aux9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string aux10 {
            get {
                return this.aux10Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux10Field, value) != true)) {
                    this.aux10Field = value;
                    this.RaisePropertyChanged("aux10");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Empresa.WS_EmpresaSoap")]
    public interface WS_EmpresaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        SitioWeb.WS_Empresa.SelectResponse Select(SitioWeb.WS_Empresa.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectResponse> SelectAsync(SitioWeb.WS_Empresa.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        SitioWeb.WS_Empresa.SelectFirstResponse SelectFirst(SitioWeb.WS_Empresa.SelectFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Empresa.SelectFirstRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        SitioWeb.WS_Empresa.InsertIntoResponse InsertInto(SitioWeb.WS_Empresa.InsertIntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.InsertIntoResponse> InsertIntoAsync(SitioWeb.WS_Empresa.InsertIntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        SitioWeb.WS_Empresa.UpdateResponse Update(SitioWeb.WS_Empresa.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.UpdateResponse> UpdateAsync(SitioWeb.WS_Empresa.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        SitioWeb.WS_Empresa.DeleteResponse Delete(SitioWeb.WS_Empresa.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.DeleteResponse> DeleteAsync(SitioWeb.WS_Empresa.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(SitioWeb.WS_Empresa.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Empresa.ClassEmpresa VALUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(SitioWeb.WS_Empresa.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Empresa.ClassEmpresa[] SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(SitioWeb.WS_Empresa.ClassEmpresa[] SelectResult, string resultado) {
            this.SelectResult = SelectResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirst", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.SelectFirstRequestBody Body;
        
        public SelectFirstRequest() {
        }
        
        public SelectFirstRequest(SitioWeb.WS_Empresa.SelectFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uid_empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectFirstRequestBody() {
        }
        
        public SelectFirstRequestBody(string UidUserLogin, string uid_empresa, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.uid_empresa = uid_empresa;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.SelectFirstResponseBody Body;
        
        public SelectFirstResponse() {
        }
        
        public SelectFirstResponse(SitioWeb.WS_Empresa.SelectFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Empresa.ClassEmpresa SelectFirstResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectFirstResponseBody() {
        }
        
        public SelectFirstResponseBody(SitioWeb.WS_Empresa.ClassEmpresa SelectFirstResult, string resultado) {
            this.SelectFirstResult = SelectFirstResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertInto", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.InsertIntoRequestBody Body;
        
        public InsertIntoRequest() {
        }
        
        public InsertIntoRequest(SitioWeb.WS_Empresa.InsertIntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Empresa.ClassEmpresa VALUE;
        
        public InsertIntoRequestBody() {
        }
        
        public InsertIntoRequestBody(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.InsertIntoResponseBody Body;
        
        public InsertIntoResponse() {
        }
        
        public InsertIntoResponse(SitioWeb.WS_Empresa.InsertIntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public InsertIntoResponseBody() {
        }
        
        public InsertIntoResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SitioWeb.WS_Empresa.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Empresa.ClassEmpresa VALUE;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SitioWeb.WS_Empresa.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(SitioWeb.WS_Empresa.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Empresa.ClassEmpresa VALUE;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Empresa.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(SitioWeb.WS_Empresa.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_EmpresaSoapChannel : SitioWeb.WS_Empresa.WS_EmpresaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_EmpresaSoapClient : System.ServiceModel.ClientBase<SitioWeb.WS_Empresa.WS_EmpresaSoap>, SitioWeb.WS_Empresa.WS_EmpresaSoap {
        
        public WS_EmpresaSoapClient() {
        }
        
        public WS_EmpresaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_EmpresaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_EmpresaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_EmpresaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Empresa.SelectResponse SitioWeb.WS_Empresa.WS_EmpresaSoap.Select(SitioWeb.WS_Empresa.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public SitioWeb.WS_Empresa.ClassEmpresa[] Select(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Empresa.SelectRequest inValue = new SitioWeb.WS_Empresa.SelectRequest();
            inValue.Body = new SitioWeb.WS_Empresa.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Empresa.SelectResponse retVal = ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).Select(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectResponse> SitioWeb.WS_Empresa.WS_EmpresaSoap.SelectAsync(SitioWeb.WS_Empresa.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectResponse> SelectAsync(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE, string EstadoExistencia) {
            SitioWeb.WS_Empresa.SelectRequest inValue = new SitioWeb.WS_Empresa.SelectRequest();
            inValue.Body = new SitioWeb.WS_Empresa.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Empresa.SelectFirstResponse SitioWeb.WS_Empresa.WS_EmpresaSoap.SelectFirst(SitioWeb.WS_Empresa.SelectFirstRequest request) {
            return base.Channel.SelectFirst(request);
        }
        
        public SitioWeb.WS_Empresa.ClassEmpresa SelectFirst(string UidUserLogin, string uid_empresa, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Empresa.SelectFirstRequest inValue = new SitioWeb.WS_Empresa.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Empresa.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uid_empresa = uid_empresa;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Empresa.SelectFirstResponse retVal = ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).SelectFirst(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectFirstResponse> SitioWeb.WS_Empresa.WS_EmpresaSoap.SelectFirstAsync(SitioWeb.WS_Empresa.SelectFirstRequest request) {
            return base.Channel.SelectFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Empresa.SelectFirstResponse> SelectFirstAsync(string UidUserLogin, string uid_empresa, string EstadoExistencia) {
            SitioWeb.WS_Empresa.SelectFirstRequest inValue = new SitioWeb.WS_Empresa.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Empresa.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uid_empresa = uid_empresa;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).SelectFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Empresa.InsertIntoResponse SitioWeb.WS_Empresa.WS_EmpresaSoap.InsertInto(SitioWeb.WS_Empresa.InsertIntoRequest request) {
            return base.Channel.InsertInto(request);
        }
        
        public string InsertInto(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.InsertIntoRequest inValue = new SitioWeb.WS_Empresa.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Empresa.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Empresa.InsertIntoResponse retVal = ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).InsertInto(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.InsertIntoResponse> SitioWeb.WS_Empresa.WS_EmpresaSoap.InsertIntoAsync(SitioWeb.WS_Empresa.InsertIntoRequest request) {
            return base.Channel.InsertIntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Empresa.InsertIntoResponse> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.InsertIntoRequest inValue = new SitioWeb.WS_Empresa.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Empresa.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).InsertIntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Empresa.UpdateResponse SitioWeb.WS_Empresa.WS_EmpresaSoap.Update(SitioWeb.WS_Empresa.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.UpdateRequest inValue = new SitioWeb.WS_Empresa.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Empresa.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Empresa.UpdateResponse retVal = ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).Update(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.UpdateResponse> SitioWeb.WS_Empresa.WS_EmpresaSoap.UpdateAsync(SitioWeb.WS_Empresa.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Empresa.UpdateResponse> UpdateAsync(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.UpdateRequest inValue = new SitioWeb.WS_Empresa.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Empresa.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Empresa.DeleteResponse SitioWeb.WS_Empresa.WS_EmpresaSoap.Delete(SitioWeb.WS_Empresa.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.DeleteRequest inValue = new SitioWeb.WS_Empresa.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Empresa.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Empresa.DeleteResponse retVal = ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).Delete(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Empresa.DeleteResponse> SitioWeb.WS_Empresa.WS_EmpresaSoap.DeleteAsync(SitioWeb.WS_Empresa.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Empresa.DeleteResponse> DeleteAsync(string UidUserLogin, SitioWeb.WS_Empresa.ClassEmpresa VALUE) {
            SitioWeb.WS_Empresa.DeleteRequest inValue = new SitioWeb.WS_Empresa.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Empresa.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Empresa.WS_EmpresaSoap)(this)).DeleteAsync(inValue);
        }
    }
}
