//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Tipocomentario {
    
    
    public partial class Tipocomentario_CU_MostrarUnico {
       


	   
			       
                /// <summary>
                /// Control lbl_uidtipocomentario_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidtipocomentario_select;
        
                /// <summary>
                /// Control txt_uidtipocomentario_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_uidtipocomentario_select;  
			       
                /// <summary>
                /// Control lbl_tipocomentario_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_tipocomentario_select;
        
                /// <summary>
                /// Control txt_tipocomentario_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_tipocomentario_select;  
	      /// <summary>
        /// txt_buscarSelectUIDTipocomentario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_buscarSelectUIDTipocomentario;
        
		   /// <summary>
        /// btnSelectTipocomentarioMostrarModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSelectTipocomentarioMostrarModal;
        



    }
}
