//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Cliente {
        
        /// <summary>
        /// Cliente_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_Insert Cliente_CU_Insert;
        
        /// <summary>
        /// Cliente_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_Update Cliente_CU_Update;
        
        /// <summary>
        /// Cliente_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_Delete Cliente_CU_Delete;
        
        /// <summary>
        /// Cliente_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_Detalle Cliente_CU_Detalle;
        
        /// <summary>
        /// Cliente_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Cliente.Cliente_CU_MostrarUnico Cliente_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
