//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Errores {
        
        /// <summary>
        /// Errores_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Errores.Errores_CU_Insert Errores_CU_Insert;
        
        /// <summary>
        /// Errores_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Errores.Errores_CU_Update Errores_CU_Update;
        
        /// <summary>
        /// Errores_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Errores.Errores_CU_Delete Errores_CU_Delete;
        
        /// <summary>
        /// Errores_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Errores.Errores_CU_Detalle Errores_CU_Detalle;
        
        /// <summary>
        /// Errores_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Errores.Errores_CU_MostrarUnico Errores_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
