//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Proceso {
        
        /// <summary>
        /// Proceso_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Proceso.Proceso_CU_Insert Proceso_CU_Insert;
        
        /// <summary>
        /// Proceso_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Proceso.Proceso_CU_Update Proceso_CU_Update;
        
        /// <summary>
        /// Proceso_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Proceso.Proceso_CU_Delete Proceso_CU_Delete;
        
        /// <summary>
        /// Proceso_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Proceso.Proceso_CU_Detalle Proceso_CU_Detalle;
        
        /// <summary>
        /// Proceso_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Proceso.Proceso_CU_MostrarUnico Proceso_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
