//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Rol {
        
        /// <summary>
        /// Rol_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Rol.Rol_CU_Insert Rol_CU_Insert;
        
        /// <summary>
        /// Rol_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Rol.Rol_CU_Update Rol_CU_Update;
        
        /// <summary>
        /// Rol_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Rol.Rol_CU_Delete Rol_CU_Delete;
        
        /// <summary>
        /// Rol_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Rol.Rol_CU_Detalle Rol_CU_Detalle;
        
        /// <summary>
        /// Rol_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Rol.Rol_CU_MostrarUnico Rol_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
