//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Tipocomentario {
        
        /// <summary>
        /// Tipocomentario_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipocomentario.Tipocomentario_CU_Insert Tipocomentario_CU_Insert;
        
        /// <summary>
        /// Tipocomentario_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipocomentario.Tipocomentario_CU_Update Tipocomentario_CU_Update;
        
        /// <summary>
        /// Tipocomentario_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipocomentario.Tipocomentario_CU_Delete Tipocomentario_CU_Delete;
        
        /// <summary>
        /// Tipocomentario_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipocomentario.Tipocomentario_CU_Detalle Tipocomentario_CU_Detalle;
        
        /// <summary>
        /// Tipocomentario_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipocomentario.Tipocomentario_CU_MostrarUnico Tipocomentario_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
