//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms {
    
    
    public partial class Tipoidentificacion {
        
        /// <summary>
        /// Tipoidentificacion_CU_Insert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipoidentificacion.Tipoidentificacion_CU_Insert Tipoidentificacion_CU_Insert;
        
        /// <summary>
        /// Tipoidentificacion_CU_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipoidentificacion.Tipoidentificacion_CU_Update Tipoidentificacion_CU_Update;
        
        /// <summary>
        /// Tipoidentificacion_CU_Delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipoidentificacion.Tipoidentificacion_CU_Delete Tipoidentificacion_CU_Delete;
        
        /// <summary>
        /// Tipoidentificacion_CU_Detalle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipoidentificacion.Tipoidentificacion_CU_Detalle Tipoidentificacion_CU_Detalle;
        
        /// <summary>
        /// Tipoidentificacion_CU_Select control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.Tipoidentificacion.Tipoidentificacion_CU_MostrarUnico Tipoidentificacion_CU_Select;
        
        /// <summary>
        /// MsgControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SitioWeb.Forms.ControlUser.MsgControl MsgControl;
    }
}
