//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.WS_Loginuser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassLoginuser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassLoginuser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidrolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux10Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uidsuario {
            get {
                return this.uidsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.uidsuarioField, value) != true)) {
                    this.uidsuarioField = value;
                    this.RaisePropertyChanged("uidsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string uidrol {
            get {
                return this.uidrolField;
            }
            set {
                if ((object.ReferenceEquals(this.uidrolField, value) != true)) {
                    this.uidrolField = value;
                    this.RaisePropertyChanged("uidrol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string aux1 {
            get {
                return this.aux1Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux1Field, value) != true)) {
                    this.aux1Field = value;
                    this.RaisePropertyChanged("aux1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string aux2 {
            get {
                return this.aux2Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux2Field, value) != true)) {
                    this.aux2Field = value;
                    this.RaisePropertyChanged("aux2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string aux3 {
            get {
                return this.aux3Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux3Field, value) != true)) {
                    this.aux3Field = value;
                    this.RaisePropertyChanged("aux3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string aux4 {
            get {
                return this.aux4Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux4Field, value) != true)) {
                    this.aux4Field = value;
                    this.RaisePropertyChanged("aux4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string aux5 {
            get {
                return this.aux5Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux5Field, value) != true)) {
                    this.aux5Field = value;
                    this.RaisePropertyChanged("aux5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string aux6 {
            get {
                return this.aux6Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux6Field, value) != true)) {
                    this.aux6Field = value;
                    this.RaisePropertyChanged("aux6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string aux7 {
            get {
                return this.aux7Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux7Field, value) != true)) {
                    this.aux7Field = value;
                    this.RaisePropertyChanged("aux7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string aux8 {
            get {
                return this.aux8Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux8Field, value) != true)) {
                    this.aux8Field = value;
                    this.RaisePropertyChanged("aux8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string aux9 {
            get {
                return this.aux9Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux9Field, value) != true)) {
                    this.aux9Field = value;
                    this.RaisePropertyChanged("aux9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string aux10 {
            get {
                return this.aux10Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux10Field, value) != true)) {
                    this.aux10Field = value;
                    this.RaisePropertyChanged("aux10");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Loginuser.WS_LoginuserSoap")]
    public interface WS_LoginuserSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        SitioWeb.WS_Loginuser.SelectResponse Select(SitioWeb.WS_Loginuser.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectResponse> SelectAsync(SitioWeb.WS_Loginuser.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        SitioWeb.WS_Loginuser.SelectFirstResponse SelectFirst(SitioWeb.WS_Loginuser.SelectFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Loginuser.SelectFirstRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        SitioWeb.WS_Loginuser.InsertIntoResponse InsertInto(SitioWeb.WS_Loginuser.InsertIntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.InsertIntoResponse> InsertIntoAsync(SitioWeb.WS_Loginuser.InsertIntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        SitioWeb.WS_Loginuser.UpdateResponse Update(SitioWeb.WS_Loginuser.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.UpdateResponse> UpdateAsync(SitioWeb.WS_Loginuser.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        SitioWeb.WS_Loginuser.DeleteResponse Delete(SitioWeb.WS_Loginuser.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.DeleteResponse> DeleteAsync(SitioWeb.WS_Loginuser.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(SitioWeb.WS_Loginuser.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Loginuser.ClassLoginuser VALUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(SitioWeb.WS_Loginuser.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Loginuser.ClassLoginuser[] SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(SitioWeb.WS_Loginuser.ClassLoginuser[] SelectResult, string resultado) {
            this.SelectResult = SelectResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirst", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.SelectFirstRequestBody Body;
        
        public SelectFirstRequest() {
        }
        
        public SelectFirstRequest(SitioWeb.WS_Loginuser.SelectFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uidsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectFirstRequestBody() {
        }
        
        public SelectFirstRequestBody(string UidUserLogin, string uidsuario, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.uidsuario = uidsuario;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.SelectFirstResponseBody Body;
        
        public SelectFirstResponse() {
        }
        
        public SelectFirstResponse(SitioWeb.WS_Loginuser.SelectFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Loginuser.ClassLoginuser SelectFirstResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectFirstResponseBody() {
        }
        
        public SelectFirstResponseBody(SitioWeb.WS_Loginuser.ClassLoginuser SelectFirstResult, string resultado) {
            this.SelectFirstResult = SelectFirstResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertInto", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.InsertIntoRequestBody Body;
        
        public InsertIntoRequest() {
        }
        
        public InsertIntoRequest(SitioWeb.WS_Loginuser.InsertIntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Loginuser.ClassLoginuser VALUE;
        
        public InsertIntoRequestBody() {
        }
        
        public InsertIntoRequestBody(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.InsertIntoResponseBody Body;
        
        public InsertIntoResponse() {
        }
        
        public InsertIntoResponse(SitioWeb.WS_Loginuser.InsertIntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public InsertIntoResponseBody() {
        }
        
        public InsertIntoResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SitioWeb.WS_Loginuser.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Loginuser.ClassLoginuser VALUE;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SitioWeb.WS_Loginuser.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(SitioWeb.WS_Loginuser.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Loginuser.ClassLoginuser VALUE;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Loginuser.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(SitioWeb.WS_Loginuser.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_LoginuserSoapChannel : SitioWeb.WS_Loginuser.WS_LoginuserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_LoginuserSoapClient : System.ServiceModel.ClientBase<SitioWeb.WS_Loginuser.WS_LoginuserSoap>, SitioWeb.WS_Loginuser.WS_LoginuserSoap {
        
        public WS_LoginuserSoapClient() {
        }
        
        public WS_LoginuserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_LoginuserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_LoginuserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_LoginuserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Loginuser.SelectResponse SitioWeb.WS_Loginuser.WS_LoginuserSoap.Select(SitioWeb.WS_Loginuser.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public SitioWeb.WS_Loginuser.ClassLoginuser[] Select(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Loginuser.SelectRequest inValue = new SitioWeb.WS_Loginuser.SelectRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Loginuser.SelectResponse retVal = ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).Select(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectResponse> SitioWeb.WS_Loginuser.WS_LoginuserSoap.SelectAsync(SitioWeb.WS_Loginuser.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectResponse> SelectAsync(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE, string EstadoExistencia) {
            SitioWeb.WS_Loginuser.SelectRequest inValue = new SitioWeb.WS_Loginuser.SelectRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Loginuser.SelectFirstResponse SitioWeb.WS_Loginuser.WS_LoginuserSoap.SelectFirst(SitioWeb.WS_Loginuser.SelectFirstRequest request) {
            return base.Channel.SelectFirst(request);
        }
        
        public SitioWeb.WS_Loginuser.ClassLoginuser SelectFirst(string UidUserLogin, string uidsuario, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Loginuser.SelectFirstRequest inValue = new SitioWeb.WS_Loginuser.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidsuario = uidsuario;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Loginuser.SelectFirstResponse retVal = ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).SelectFirst(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectFirstResponse> SitioWeb.WS_Loginuser.WS_LoginuserSoap.SelectFirstAsync(SitioWeb.WS_Loginuser.SelectFirstRequest request) {
            return base.Channel.SelectFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.SelectFirstResponse> SelectFirstAsync(string UidUserLogin, string uidsuario, string EstadoExistencia) {
            SitioWeb.WS_Loginuser.SelectFirstRequest inValue = new SitioWeb.WS_Loginuser.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidsuario = uidsuario;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).SelectFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Loginuser.InsertIntoResponse SitioWeb.WS_Loginuser.WS_LoginuserSoap.InsertInto(SitioWeb.WS_Loginuser.InsertIntoRequest request) {
            return base.Channel.InsertInto(request);
        }
        
        public string InsertInto(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.InsertIntoRequest inValue = new SitioWeb.WS_Loginuser.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Loginuser.InsertIntoResponse retVal = ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).InsertInto(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.InsertIntoResponse> SitioWeb.WS_Loginuser.WS_LoginuserSoap.InsertIntoAsync(SitioWeb.WS_Loginuser.InsertIntoRequest request) {
            return base.Channel.InsertIntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.InsertIntoResponse> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.InsertIntoRequest inValue = new SitioWeb.WS_Loginuser.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).InsertIntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Loginuser.UpdateResponse SitioWeb.WS_Loginuser.WS_LoginuserSoap.Update(SitioWeb.WS_Loginuser.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.UpdateRequest inValue = new SitioWeb.WS_Loginuser.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Loginuser.UpdateResponse retVal = ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).Update(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.UpdateResponse> SitioWeb.WS_Loginuser.WS_LoginuserSoap.UpdateAsync(SitioWeb.WS_Loginuser.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.UpdateResponse> UpdateAsync(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.UpdateRequest inValue = new SitioWeb.WS_Loginuser.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Loginuser.DeleteResponse SitioWeb.WS_Loginuser.WS_LoginuserSoap.Delete(SitioWeb.WS_Loginuser.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.DeleteRequest inValue = new SitioWeb.WS_Loginuser.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Loginuser.DeleteResponse retVal = ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).Delete(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.DeleteResponse> SitioWeb.WS_Loginuser.WS_LoginuserSoap.DeleteAsync(SitioWeb.WS_Loginuser.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Loginuser.DeleteResponse> DeleteAsync(string UidUserLogin, SitioWeb.WS_Loginuser.ClassLoginuser VALUE) {
            SitioWeb.WS_Loginuser.DeleteRequest inValue = new SitioWeb.WS_Loginuser.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Loginuser.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Loginuser.WS_LoginuserSoap)(this)).DeleteAsync(inValue);
        }
    }
}
