//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.WS_Grupousuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassGrupousuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassGrupousuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidgrupousuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidgrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidusuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux10Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uidgrupousuario {
            get {
                return this.uidgrupousuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.uidgrupousuarioField, value) != true)) {
                    this.uidgrupousuarioField = value;
                    this.RaisePropertyChanged("uidgrupousuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uidgrupo {
            get {
                return this.uidgrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.uidgrupoField, value) != true)) {
                    this.uidgrupoField = value;
                    this.RaisePropertyChanged("uidgrupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uidusuario {
            get {
                return this.uidusuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.uidusuarioField, value) != true)) {
                    this.uidusuarioField = value;
                    this.RaisePropertyChanged("uidusuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string aux1 {
            get {
                return this.aux1Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux1Field, value) != true)) {
                    this.aux1Field = value;
                    this.RaisePropertyChanged("aux1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string aux2 {
            get {
                return this.aux2Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux2Field, value) != true)) {
                    this.aux2Field = value;
                    this.RaisePropertyChanged("aux2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string aux3 {
            get {
                return this.aux3Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux3Field, value) != true)) {
                    this.aux3Field = value;
                    this.RaisePropertyChanged("aux3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string aux4 {
            get {
                return this.aux4Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux4Field, value) != true)) {
                    this.aux4Field = value;
                    this.RaisePropertyChanged("aux4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string aux5 {
            get {
                return this.aux5Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux5Field, value) != true)) {
                    this.aux5Field = value;
                    this.RaisePropertyChanged("aux5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string aux6 {
            get {
                return this.aux6Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux6Field, value) != true)) {
                    this.aux6Field = value;
                    this.RaisePropertyChanged("aux6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string aux7 {
            get {
                return this.aux7Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux7Field, value) != true)) {
                    this.aux7Field = value;
                    this.RaisePropertyChanged("aux7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string aux8 {
            get {
                return this.aux8Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux8Field, value) != true)) {
                    this.aux8Field = value;
                    this.RaisePropertyChanged("aux8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string aux9 {
            get {
                return this.aux9Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux9Field, value) != true)) {
                    this.aux9Field = value;
                    this.RaisePropertyChanged("aux9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string aux10 {
            get {
                return this.aux10Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux10Field, value) != true)) {
                    this.aux10Field = value;
                    this.RaisePropertyChanged("aux10");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Grupousuario.WS_GrupousuarioSoap")]
    public interface WS_GrupousuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        SitioWeb.WS_Grupousuario.SelectResponse Select(SitioWeb.WS_Grupousuario.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectResponse> SelectAsync(SitioWeb.WS_Grupousuario.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        SitioWeb.WS_Grupousuario.SelectFirstResponse SelectFirst(SitioWeb.WS_Grupousuario.SelectFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Grupousuario.SelectFirstRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        SitioWeb.WS_Grupousuario.InsertIntoResponse InsertInto(SitioWeb.WS_Grupousuario.InsertIntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.InsertIntoResponse> InsertIntoAsync(SitioWeb.WS_Grupousuario.InsertIntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        SitioWeb.WS_Grupousuario.UpdateResponse Update(SitioWeb.WS_Grupousuario.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.UpdateResponse> UpdateAsync(SitioWeb.WS_Grupousuario.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        SitioWeb.WS_Grupousuario.DeleteResponse Delete(SitioWeb.WS_Grupousuario.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.DeleteResponse> DeleteAsync(SitioWeb.WS_Grupousuario.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(SitioWeb.WS_Grupousuario.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(SitioWeb.WS_Grupousuario.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario[] SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(SitioWeb.WS_Grupousuario.ClassGrupousuario[] SelectResult, string resultado) {
            this.SelectResult = SelectResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirst", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.SelectFirstRequestBody Body;
        
        public SelectFirstRequest() {
        }
        
        public SelectFirstRequest(SitioWeb.WS_Grupousuario.SelectFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uidgrupousuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectFirstRequestBody() {
        }
        
        public SelectFirstRequestBody(string UidUserLogin, string uidgrupousuario, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.uidgrupousuario = uidgrupousuario;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.SelectFirstResponseBody Body;
        
        public SelectFirstResponse() {
        }
        
        public SelectFirstResponse(SitioWeb.WS_Grupousuario.SelectFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario SelectFirstResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectFirstResponseBody() {
        }
        
        public SelectFirstResponseBody(SitioWeb.WS_Grupousuario.ClassGrupousuario SelectFirstResult, string resultado) {
            this.SelectFirstResult = SelectFirstResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertInto", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.InsertIntoRequestBody Body;
        
        public InsertIntoRequest() {
        }
        
        public InsertIntoRequest(SitioWeb.WS_Grupousuario.InsertIntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE;
        
        public InsertIntoRequestBody() {
        }
        
        public InsertIntoRequestBody(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.InsertIntoResponseBody Body;
        
        public InsertIntoResponse() {
        }
        
        public InsertIntoResponse(SitioWeb.WS_Grupousuario.InsertIntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public InsertIntoResponseBody() {
        }
        
        public InsertIntoResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SitioWeb.WS_Grupousuario.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SitioWeb.WS_Grupousuario.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(SitioWeb.WS_Grupousuario.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Grupousuario.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(SitioWeb.WS_Grupousuario.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GrupousuarioSoapChannel : SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GrupousuarioSoapClient : System.ServiceModel.ClientBase<SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap>, SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap {
        
        public WS_GrupousuarioSoapClient() {
        }
        
        public WS_GrupousuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GrupousuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GrupousuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GrupousuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Grupousuario.SelectResponse SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.Select(SitioWeb.WS_Grupousuario.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public SitioWeb.WS_Grupousuario.ClassGrupousuario[] Select(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Grupousuario.SelectRequest inValue = new SitioWeb.WS_Grupousuario.SelectRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Grupousuario.SelectResponse retVal = ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).Select(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectResponse> SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.SelectAsync(SitioWeb.WS_Grupousuario.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectResponse> SelectAsync(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE, string EstadoExistencia) {
            SitioWeb.WS_Grupousuario.SelectRequest inValue = new SitioWeb.WS_Grupousuario.SelectRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Grupousuario.SelectFirstResponse SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.SelectFirst(SitioWeb.WS_Grupousuario.SelectFirstRequest request) {
            return base.Channel.SelectFirst(request);
        }
        
        public SitioWeb.WS_Grupousuario.ClassGrupousuario SelectFirst(string UidUserLogin, string uidgrupousuario, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Grupousuario.SelectFirstRequest inValue = new SitioWeb.WS_Grupousuario.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidgrupousuario = uidgrupousuario;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Grupousuario.SelectFirstResponse retVal = ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).SelectFirst(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectFirstResponse> SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.SelectFirstAsync(SitioWeb.WS_Grupousuario.SelectFirstRequest request) {
            return base.Channel.SelectFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.SelectFirstResponse> SelectFirstAsync(string UidUserLogin, string uidgrupousuario, string EstadoExistencia) {
            SitioWeb.WS_Grupousuario.SelectFirstRequest inValue = new SitioWeb.WS_Grupousuario.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidgrupousuario = uidgrupousuario;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).SelectFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Grupousuario.InsertIntoResponse SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.InsertInto(SitioWeb.WS_Grupousuario.InsertIntoRequest request) {
            return base.Channel.InsertInto(request);
        }
        
        public string InsertInto(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.InsertIntoRequest inValue = new SitioWeb.WS_Grupousuario.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Grupousuario.InsertIntoResponse retVal = ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).InsertInto(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.InsertIntoResponse> SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.InsertIntoAsync(SitioWeb.WS_Grupousuario.InsertIntoRequest request) {
            return base.Channel.InsertIntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.InsertIntoResponse> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.InsertIntoRequest inValue = new SitioWeb.WS_Grupousuario.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).InsertIntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Grupousuario.UpdateResponse SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.Update(SitioWeb.WS_Grupousuario.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.UpdateRequest inValue = new SitioWeb.WS_Grupousuario.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Grupousuario.UpdateResponse retVal = ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).Update(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.UpdateResponse> SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.UpdateAsync(SitioWeb.WS_Grupousuario.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.UpdateResponse> UpdateAsync(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.UpdateRequest inValue = new SitioWeb.WS_Grupousuario.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Grupousuario.DeleteResponse SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.Delete(SitioWeb.WS_Grupousuario.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.DeleteRequest inValue = new SitioWeb.WS_Grupousuario.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Grupousuario.DeleteResponse retVal = ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).Delete(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.DeleteResponse> SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap.DeleteAsync(SitioWeb.WS_Grupousuario.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Grupousuario.DeleteResponse> DeleteAsync(string UidUserLogin, SitioWeb.WS_Grupousuario.ClassGrupousuario VALUE) {
            SitioWeb.WS_Grupousuario.DeleteRequest inValue = new SitioWeb.WS_Grupousuario.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Grupousuario.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Grupousuario.WS_GrupousuarioSoap)(this)).DeleteAsync(inValue);
        }
    }
}
