//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Menu {
    
    
    public partial class Menu_CU_MostrarUnico {
       


	   
			       
                /// <summary>
                /// Control lbl_uidmenu_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidmenu_select;
        
                /// <summary>
                /// Control txt_uidmenu_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_uidmenu_select;  
			       
                /// <summary>
                /// Control lbl_uidrol_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidrol_select;
        
                /// <summary>
                /// Control cb_uidrol_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList cb_uidrol_select;  
			       
                /// <summary>
                /// Control lbl_uidpagina_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidpagina_select;
        
                /// <summary>
                /// Control cb_uidpagina_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList cb_uidpagina_select;  
			       
                /// <summary>
                /// Control lbl_esvisible_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_esvisible_select;
        
                /// <summary>
                /// Control checkb_esvisible_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.CheckBox checkb_esvisible_select;  
			       
                /// <summary>
                /// Control lbl_semuestra_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_semuestra_select;
        
                /// <summary>
                /// Control checkb_semuestra_select.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.CheckBox checkb_semuestra_select;  
	      /// <summary>
        /// txt_buscarSelectUIDMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_buscarSelectUIDMenu;
        
		   /// <summary>
        /// btnSelectMenuMostrarModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSelectMenuMostrarModal;
        



    }
}
