//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Menu {
    
    
    public partial class Menu_CU_Delete {
        
    
        /// <summary>
        /// txt_buscarDeleteUIDMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_buscarDeleteUIDMenu;
        
		
        /// <summary>
        /// btnDeleteMenuMostrarModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnDeleteMenuMostrarModal;
        
		
			       
                /// <summary>
                /// Control lbl_uidmenu_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidmenu_delete;
        
                /// <summary>
                /// Control txt_uidmenu_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_uidmenu_delete;  
			       
                /// <summary>
                /// Control lbl_uidrol_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidrol_delete;
        
                /// <summary>
                /// Control cb_uidrol_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList cb_uidrol_delete;  
			       
                /// <summary>
                /// Control lbl_uidpagina_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidpagina_delete;
        
                /// <summary>
                /// Control cb_uidpagina_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.DropDownList cb_uidpagina_delete;  
			       
                /// <summary>
                /// Control lbl_esvisible_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_esvisible_delete;
        
                /// <summary>
                /// Control checkb_esvisible_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.CheckBox checkb_esvisible_delete;  
			       
                /// <summary>
                /// Control lbl_semuestra_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_semuestra_delete;
        
                /// <summary>
                /// Control checkb_semuestra_delete.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.CheckBox checkb_semuestra_delete;  
        
        /// <summary>
        /// lblMensajeError_delete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMensajeError_delete;
        
        /// <summary>
        /// btnGuardarEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGuardarEliminar;

	}
}
