//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Forms.ControlUser.Tipopersona {
    
    
    public partial class Tipopersona_CU_Update {
        
		 /// <summary>
        /// txt_buscarUpdateUIDTipopersona control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txt_buscarUpdateUIDTipopersona;
        
        /// <summary>
        /// btnUpdateTipopersonaMostrarModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnUpdateTipopersonaMostrarModal;
       

	   
			       
                /// <summary>
                /// Control lbl_uidtipopersona_update.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_uidtipopersona_update;
        
                /// <summary>
                /// Control txt_uidtipopersona_update.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_uidtipopersona_update;  
			       
                /// <summary>
                /// Control lbl_tipopersona_update.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.Label lbl_tipopersona_update;
        
                /// <summary>
                /// Control txt_tipopersona_update.
                /// </summary>
                /// <remarks>
                /// Campo generado automáticamente.
                /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
                /// </remarks>
                protected global::System.Web.UI.WebControls.TextBox txt_tipopersona_update;  

	   
        /// <summary>
        /// lblMensajeError_update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMensajeError_update;
        
        /// <summary>
        /// btnGuardarEditar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGuardarEditar;
     
	 }
}
