//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.WS_Nivelestudio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassNivelestudio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClassNivelestudio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidnivelestudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivelestudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aux10Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uidnivelestudio {
            get {
                return this.uidnivelestudioField;
            }
            set {
                if ((object.ReferenceEquals(this.uidnivelestudioField, value) != true)) {
                    this.uidnivelestudioField = value;
                    this.RaisePropertyChanged("uidnivelestudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nivelestudio {
            get {
                return this.nivelestudioField;
            }
            set {
                if ((object.ReferenceEquals(this.nivelestudioField, value) != true)) {
                    this.nivelestudioField = value;
                    this.RaisePropertyChanged("nivelestudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aux1 {
            get {
                return this.aux1Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux1Field, value) != true)) {
                    this.aux1Field = value;
                    this.RaisePropertyChanged("aux1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string aux2 {
            get {
                return this.aux2Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux2Field, value) != true)) {
                    this.aux2Field = value;
                    this.RaisePropertyChanged("aux2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string aux3 {
            get {
                return this.aux3Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux3Field, value) != true)) {
                    this.aux3Field = value;
                    this.RaisePropertyChanged("aux3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string aux4 {
            get {
                return this.aux4Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux4Field, value) != true)) {
                    this.aux4Field = value;
                    this.RaisePropertyChanged("aux4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string aux5 {
            get {
                return this.aux5Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux5Field, value) != true)) {
                    this.aux5Field = value;
                    this.RaisePropertyChanged("aux5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string aux6 {
            get {
                return this.aux6Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux6Field, value) != true)) {
                    this.aux6Field = value;
                    this.RaisePropertyChanged("aux6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string aux7 {
            get {
                return this.aux7Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux7Field, value) != true)) {
                    this.aux7Field = value;
                    this.RaisePropertyChanged("aux7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string aux8 {
            get {
                return this.aux8Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux8Field, value) != true)) {
                    this.aux8Field = value;
                    this.RaisePropertyChanged("aux8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string aux9 {
            get {
                return this.aux9Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux9Field, value) != true)) {
                    this.aux9Field = value;
                    this.RaisePropertyChanged("aux9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string aux10 {
            get {
                return this.aux10Field;
            }
            set {
                if ((object.ReferenceEquals(this.aux10Field, value) != true)) {
                    this.aux10Field = value;
                    this.RaisePropertyChanged("aux10");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Nivelestudio.WS_NivelestudioSoap")]
    public interface WS_NivelestudioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        SitioWeb.WS_Nivelestudio.SelectResponse Select(SitioWeb.WS_Nivelestudio.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectResponse> SelectAsync(SitioWeb.WS_Nivelestudio.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        SitioWeb.WS_Nivelestudio.SelectFirstResponse SelectFirst(SitioWeb.WS_Nivelestudio.SelectFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectFirstResponse> SelectFirstAsync(SitioWeb.WS_Nivelestudio.SelectFirstRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        SitioWeb.WS_Nivelestudio.InsertIntoResponse InsertInto(SitioWeb.WS_Nivelestudio.InsertIntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertInto", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.InsertIntoResponse> InsertIntoAsync(SitioWeb.WS_Nivelestudio.InsertIntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        SitioWeb.WS_Nivelestudio.UpdateResponse Update(SitioWeb.WS_Nivelestudio.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.UpdateResponse> UpdateAsync(SitioWeb.WS_Nivelestudio.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UidUserLogin del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        SitioWeb.WS_Nivelestudio.DeleteResponse Delete(SitioWeb.WS_Nivelestudio.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.DeleteResponse> DeleteAsync(SitioWeb.WS_Nivelestudio.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(SitioWeb.WS_Nivelestudio.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(SitioWeb.WS_Nivelestudio.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio[] SelectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(SitioWeb.WS_Nivelestudio.ClassNivelestudio[] SelectResult, string resultado) {
            this.SelectResult = SelectResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirst", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.SelectFirstRequestBody Body;
        
        public SelectFirstRequest() {
        }
        
        public SelectFirstRequest(SitioWeb.WS_Nivelestudio.SelectFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string uidnivelestudio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EstadoExistencia;
        
        public SelectFirstRequestBody() {
        }
        
        public SelectFirstRequestBody(string UidUserLogin, string uidnivelestudio, string EstadoExistencia) {
            this.UidUserLogin = UidUserLogin;
            this.uidnivelestudio = uidnivelestudio;
            this.EstadoExistencia = EstadoExistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectFirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.SelectFirstResponseBody Body;
        
        public SelectFirstResponse() {
        }
        
        public SelectFirstResponse(SitioWeb.WS_Nivelestudio.SelectFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio SelectFirstResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string resultado;
        
        public SelectFirstResponseBody() {
        }
        
        public SelectFirstResponseBody(SitioWeb.WS_Nivelestudio.ClassNivelestudio SelectFirstResult, string resultado) {
            this.SelectFirstResult = SelectFirstResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertInto", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.InsertIntoRequestBody Body;
        
        public InsertIntoRequest() {
        }
        
        public InsertIntoRequest(SitioWeb.WS_Nivelestudio.InsertIntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE;
        
        public InsertIntoRequestBody() {
        }
        
        public InsertIntoRequestBody(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.InsertIntoResponseBody Body;
        
        public InsertIntoResponse() {
        }
        
        public InsertIntoResponse(SitioWeb.WS_Nivelestudio.InsertIntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public InsertIntoResponseBody() {
        }
        
        public InsertIntoResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SitioWeb.WS_Nivelestudio.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SitioWeb.WS_Nivelestudio.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(SitioWeb.WS_Nivelestudio.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UidUserLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            this.UidUserLogin = UidUserLogin;
            this.VALUE = VALUE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.WS_Nivelestudio.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(SitioWeb.WS_Nivelestudio.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string resultado;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(string resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_NivelestudioSoapChannel : SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_NivelestudioSoapClient : System.ServiceModel.ClientBase<SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap>, SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap {
        
        public WS_NivelestudioSoapClient() {
        }
        
        public WS_NivelestudioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_NivelestudioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_NivelestudioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_NivelestudioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Nivelestudio.SelectResponse SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.Select(SitioWeb.WS_Nivelestudio.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio[] Select(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Nivelestudio.SelectRequest inValue = new SitioWeb.WS_Nivelestudio.SelectRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Nivelestudio.SelectResponse retVal = ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).Select(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectResponse> SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.SelectAsync(SitioWeb.WS_Nivelestudio.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectResponse> SelectAsync(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE, string EstadoExistencia) {
            SitioWeb.WS_Nivelestudio.SelectRequest inValue = new SitioWeb.WS_Nivelestudio.SelectRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.SelectRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Nivelestudio.SelectFirstResponse SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.SelectFirst(SitioWeb.WS_Nivelestudio.SelectFirstRequest request) {
            return base.Channel.SelectFirst(request);
        }
        
        public SitioWeb.WS_Nivelestudio.ClassNivelestudio SelectFirst(string UidUserLogin, string uidnivelestudio, string EstadoExistencia, out string resultado) {
            SitioWeb.WS_Nivelestudio.SelectFirstRequest inValue = new SitioWeb.WS_Nivelestudio.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidnivelestudio = uidnivelestudio;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            SitioWeb.WS_Nivelestudio.SelectFirstResponse retVal = ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).SelectFirst(inValue);
            resultado = retVal.Body.resultado;
            return retVal.Body.SelectFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectFirstResponse> SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.SelectFirstAsync(SitioWeb.WS_Nivelestudio.SelectFirstRequest request) {
            return base.Channel.SelectFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.SelectFirstResponse> SelectFirstAsync(string UidUserLogin, string uidnivelestudio, string EstadoExistencia) {
            SitioWeb.WS_Nivelestudio.SelectFirstRequest inValue = new SitioWeb.WS_Nivelestudio.SelectFirstRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.SelectFirstRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.uidnivelestudio = uidnivelestudio;
            inValue.Body.EstadoExistencia = EstadoExistencia;
            return ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).SelectFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Nivelestudio.InsertIntoResponse SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.InsertInto(SitioWeb.WS_Nivelestudio.InsertIntoRequest request) {
            return base.Channel.InsertInto(request);
        }
        
        public string InsertInto(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.InsertIntoRequest inValue = new SitioWeb.WS_Nivelestudio.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Nivelestudio.InsertIntoResponse retVal = ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).InsertInto(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.InsertIntoResponse> SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.InsertIntoAsync(SitioWeb.WS_Nivelestudio.InsertIntoRequest request) {
            return base.Channel.InsertIntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.InsertIntoResponse> InsertIntoAsync(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.InsertIntoRequest inValue = new SitioWeb.WS_Nivelestudio.InsertIntoRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.InsertIntoRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).InsertIntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Nivelestudio.UpdateResponse SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.Update(SitioWeb.WS_Nivelestudio.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.UpdateRequest inValue = new SitioWeb.WS_Nivelestudio.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Nivelestudio.UpdateResponse retVal = ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).Update(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.UpdateResponse> SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.UpdateAsync(SitioWeb.WS_Nivelestudio.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.UpdateResponse> UpdateAsync(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.UpdateRequest inValue = new SitioWeb.WS_Nivelestudio.UpdateRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.UpdateRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.WS_Nivelestudio.DeleteResponse SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.Delete(SitioWeb.WS_Nivelestudio.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.DeleteRequest inValue = new SitioWeb.WS_Nivelestudio.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            SitioWeb.WS_Nivelestudio.DeleteResponse retVal = ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).Delete(inValue);
            return retVal.Body.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.DeleteResponse> SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap.DeleteAsync(SitioWeb.WS_Nivelestudio.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.WS_Nivelestudio.DeleteResponse> DeleteAsync(string UidUserLogin, SitioWeb.WS_Nivelestudio.ClassNivelestudio VALUE) {
            SitioWeb.WS_Nivelestudio.DeleteRequest inValue = new SitioWeb.WS_Nivelestudio.DeleteRequest();
            inValue.Body = new SitioWeb.WS_Nivelestudio.DeleteRequestBody();
            inValue.Body.UidUserLogin = UidUserLogin;
            inValue.Body.VALUE = VALUE;
            return ((SitioWeb.WS_Nivelestudio.WS_NivelestudioSoap)(this)).DeleteAsync(inValue);
        }
    }
}
